<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOaKAN3N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOaKAN3N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOaKAN3N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOaKAN3N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOaKAN3N\App_KernelDevDebugContainer([
    'container.build_hash' => 'OaKAN3N',
    'container.build_id' => '41c3e7ea',
    'container.build_time' => 1628129330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOaKAN3N');
