<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8Enmxms\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8Enmxms/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8Enmxms.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8Enmxms\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8Enmxms\App_KernelDevDebugContainer([
    'container.build_hash' => '8Enmxms',
    'container.build_id' => '82302108',
    'container.build_time' => 1628135724,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8Enmxms');
