<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRZKx0S1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRZKx0S1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRZKx0S1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRZKx0S1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRZKx0S1\App_KernelDevDebugContainer([
    'container.build_hash' => 'RZKx0S1',
    'container.build_id' => 'e34e7e43',
    'container.build_time' => 1628132074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRZKx0S1');
