<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'listar_libro' => [[], ['_controller' => 'App\\Controller\\LibroController::listarLibro'], [], [['text', '/libro/listar']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
